<!doctype html>
<html dir="<?php echo $this->I18N->getDir(); ?>" lang="<?php echo $this->locale; ?>">

<head>
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <![endif]-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Patrolling wiki, enhanced!">
    <meta name="author" content="Kenrick">
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/light.min.css'>
    <link rel="stylesheet" href="dist/bundle.css">

    <title><?php echo $this->title; ?></title>
    <script>
        var LOCALE = '<?php echo $this->locale; ?>' || 'en';
        var PROJECT_SUBDOMAIN = '<?php echo $this->language; ?>' || 'en';
        var PROJECT_NAME = '<?php echo $this->project; ?>' || 'wikipedia';
        var DBNAMES = <?php
                        if (isset($this->dbname)) {
                            echo "'" . json_encode($this->dbname) . "'";
                        } else {
                            echo "null";
                        }
                        ?> || null;
    </script>
</head>

<body>
    <div id="app"></div>
    <script src="dist/bundle.js"></script>
</body>

</html>